services:
  - type: web
    name: product-management-backend
    env: java
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/Product_Management_System_New-0.0.1-SNAPSHOT.jar"
    envVars:
       - key: JAVA_HOME
         value: /opt/render/project/.java
      - key: DB_URL
        value: jdbc:mysql://tramway.proxy.rlwy.net:21871/railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: GndKKHIhZgDZVyTcKhWDCyNLoDLonJMN
      # - key: DB_URL
      #   value: jdbc:mysql://localhost:3306/Product_Management_System_Project
